services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  celery:
    container_name: celery
    build:
      context: ./backend/
    working_dir: /usr/src/app/src
    command: >
      sh -c "
        celery -A dcelery worker --loglevel=info
      "
    depends_on:
      - redis

  fastapi:
    container_name: fastapi
    build:
      context: ./backend/
    working_dir: /usr/src/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - OPENROUTER_API=${OPENROUTER_API}
    depends_on:
      - celery
